- name: Attente que Grafana soit disponible
  wait_for:
    host: localhost
    port: 3000
    timeout: 30
    state: started

- name: Ajout de la datasource Prometheus à Grafana
  uri:
    url: http://localhost:3000/api/datasources
    method: POST
    user: admin
    password: admin
    body: |
      {
        "name": "Prometheus",
        "type": "prometheus",
        "url": "http://localhost:9090",
        "access": "proxy",
        "basicAuth": false
      }
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: 200,409  # 409 = déjà existant
